# Generated by Django 6.0.3 on 2026-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
