# Generated by Django 6.0.3 on 2026-04-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_progress_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
