# Generated by Django 6.0.3 on 2026-04-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='image',
        ),
    ]
