# Generated by Django 6.0.3 on 2026-05-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_alter_enrollment_id_alter_exercise_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
