# Generated by Django 6.0.3 on 2026-05-11 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
