# Generated by Django 5.2.13 on 2026-05-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
