# Generated by Django 5.2.13 on 2026-05-08 10:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0001_initial"),
        ("ideas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_helpful",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.TextField(
                help_text="Commentaire détaillé (min 50 caractères)"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feasibility_score",
            field=models.PositiveSmallIntegerField(
                help_text="Faisabilité technique (0-25)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="ideas.idea",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="innovation_score",
            field=models.PositiveSmallIntegerField(
                help_text="Innovation / différenciation (0-25)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="market_score",
            field=models.PositiveSmallIntegerField(
                help_text="Potentiel de marché (0-25)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="roi_score",
            field=models.PositiveSmallIntegerField(
                help_text="Rentabilité / ROI (0-25)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25),
                ],
            ),
        ),
    ]
