# Generated by Django 6.0.3 on 2026-04-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('programs', '0007_remove_progress_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
    ]
