# Generated by Django 6.0.3 on 2026-04-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_id'),
        ('payments', '0002_payment_program'),
    ]

    operations = [
    ]
