# Generated by Django 6.0.3 on 2026-04-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_unique_constraint_payment'),
        ('payments', '0006_add_unique_constraint_payment'),
    ]

    operations = [
    ]
