# Generated by Django 6.0.4 on 2026-05-08 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignationMoniteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activite')),
                ('moniteur', models.ForeignKey(limit_choices_to={'role': 'moniteur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignation Moniteur',
                'verbose_name_plural': 'Assignations Moniteurs',
                'ordering': ['-date_assignation'],
                'unique_together': {('moniteur', 'activite')},
            },
        ),
    ]
