# Generated by Django 6.0.3 on 2026-05-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_coach_user_alter_appointment_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coach',
            name='availability',
            field=models.TextField(blank=True, default='À convenir'),
        ),
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, default='coaches/default.png', null=True, upload_to='coaches/'),
        ),
        migrations.AddField(
            model_name='coach',
            name='video_link',
            field=models.URLField(blank=True, help_text='Google Meet ou Zoom URL', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'coach', 'status'), name='unique_active_coaching_relation'),
        ),
    ]
