# Generated by Django 5.2.13 on 2026-05-08 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="type",
        ),
        migrations.AddField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("new_feedback", "Nouveau feedback"),
                    ("new_comment", "Nouveau commentaire"),
                    ("new_reply", "Nouvelle réponse"),
                    ("idea_promoted", "Idée prometteuse"),
                    ("feedback_voted", "Feedback voté"),
                    ("status_changed", "Statut modifié"),
                ],
                default="new_feedback",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
