# Generated by Django 5.2.13 on 2026-05-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_remove_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('new_feedback', 'Nouveau feedback'), ('new_comment', 'Nouveau commentaire'), ('new_reply', 'Nouvelle réponse'), ('idea_promoted', 'Idée prometteuse'), ('feedback_voted', 'Feedback voté'), ('status_changed', 'Statut modifié'), ('feedback', 'Feedback'), ('comment', 'Comment'), ('status', 'Status')], default='new_feedback', max_length=20),
        ),
    ]
