# Generated by Django 5.2.13 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(
                choices=[
                    ('new_feedback', 'New feedback'),
                    ('new_comment', 'New comment'),
                    ('new_reply', 'New reply'),
                    ('idea_promoted', 'Promising idea'),
                    ('feedback_voted', 'Feedback voted'),
                    ('status_changed', 'Status changed'),
                    ('admin_new_idea', 'New idea for moderation'),
                    ('admin_status', 'Moderation action'),
                    ('feedback', 'Feedback'),
                    ('comment', 'Comment'),
                    ('status', 'Status'),
                ],
                default='new_feedback',
                max_length=20,
            ),
        ),
    ]
