# Generated by Django 4.2.11 on 2026-05-08 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('author', 'Author'), ('admin', 'Admin')], default='user', help_text='User role in the system', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text="If True, author's articles are published automatically without review"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requested_author',
            field=models.BooleanField(default=False, help_text='User has requested to become an author'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media links as JSON'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'follow',
                'verbose_name_plural': 'follows',
                'indexes': [models.Index(fields=['follower', 'created_at'], name='users_follo_followe_229ec1_idx'), models.Index(fields=['following', 'created_at'], name='users_follo_followi_dcf251_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
