# Generated by Django 4.2.11 on 2026-05-11 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_userprofile_auto_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('author', 'Author'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', help_text='User role in the system', max_length=20),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this moderator can perform moderation actions')),
                ('articles_reviewed', models.PositiveIntegerField(default=0)),
                ('articles_approved', models.PositiveIntegerField(default=0)),
                ('articles_rejected', models.PositiveIntegerField(default=0)),
                ('comments_deleted', models.PositiveIntegerField(default=0)),
                ('can_review_articles', models.BooleanField(default=True)),
                ('can_delete_articles', models.BooleanField(default=True)),
                ('can_delete_comments', models.BooleanField(default=True)),
                ('can_manage_other_moderators', models.BooleanField(default=False, help_text='Only senior moderators can manage other moderators')),
                ('created_by', models.ForeignKey(help_text='Admin who created this moderator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderators_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User with moderator role', on_delete=django.db.models.deletion.CASCADE, related_name='moderator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moderator',
                'verbose_name_plural': 'moderators',
                'ordering': ['-created_at'],
            },
        ),
    ]
