# Generated by Django 6.0.4 on 2026-05-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('equitation', 'Équitation'), ('mer', 'Balade en Mer'), ('stage', 'Stage')], default='equitation', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duree', models.CharField(default='1h', max_length=50)),
                ('places_max', models.PositiveIntegerField(default=10)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
    ]
