# Generated by Django 4.2.11 on 2026-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Résumé court affiché dans les listes', max_length=500)),
                ('body', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/articles/')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('read_time', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Temps de lecture estimé en minutes')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('allow_comments', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
