# Generated by Django 4.2.11 on 2026-05-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='blog_articl_status_8b18ca_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='read_time',
        ),
        migrations.AddField(
            model_name='article',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text='If True, article publishes immediately without review'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='taxonomy.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Article content (can be rich text)', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Article cover image', null=True, upload_to='articles/covers/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of times article was viewed'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'created_at'], name='blog_articl_status_f7b14d_idx'),
        ),
    ]
