from django.urls import path
from . import views

app_name = 'admin_app'

urlpatterns = [
    path('dashboard/',
         views.admin_dashboard_view,
         name='dashboard'),
    path('activities/',
         views.admin_activities_view,
         name='activities'),
    path('activities/<int:pk>/delete/',
         views.admin_activity_delete,
         name='activity-delete'),
    path('reservations/',
         views.admin_reservations_view,
         name='reservations'),
    path('reservations/<int:pk>/edit/',
         views.reservation_edit,
         name='reservation-edit'),
    path('reservations/<int:pk>/confirm/',
         views.reservation_confirm,
         name='reservation-confirm'),
    path('reservations/<int:pk>/cancel/',
         views.reservation_cancel,
         name='reservation-cancel'),
    path('tickets/',
         views.admin_tickets_view,
         name='tickets'),
    path('tickets/<int:pk>/validate/',
         views.ticket_validate,
         name='ticket-validate'),
    path('users/',
         views.admin_users_view,
         name='users'),
    path('users/<int:pk>/delete/',
         views.user_delete,
         name='user-delete'),
    path('moniteurs/',
         views.admin_monitors_view,
         name='moniteurs'),
    path('statistiques/',
         views.admin_statistics_view,
         name='statistiques'),
]
