# Generated by Django 4.2.11 on 2026-05-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'New Comment'), ('reply', 'Reply to Comment'), ('like', 'Like'), ('follow', 'New Follower'), ('article_submitted', 'Review Requested'), ('article_approved', 'Article Approved'), ('article_rejected', 'Article Rejected'), ('article_saved', 'Article Saved'), ('moderator_created', 'Moderator Created'), ('moderator_action', 'Moderator Action')], db_index=True, max_length=20),
        ),
    ]
