# Generated by Django 6.0.3 on 2026-04-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Perte de poids'), ('muscle_gain', 'Prise de masse'), ('maintenance', 'Maintien'), ('general_fitness', 'Fitness général')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
